name: AranarthCore
version: 1.0
author: Aearost
main: com.aearost.Main
api-version: 1.16
description: Contains a large variety of features and functionality to be used specifically for the Aranarth Minecraft server.