name: AranarthCore
version: 1.0
author: Aearost
main: com.aearost.aranarthcore.AranarthCore
api-version: 1.16
depend: [Multiverse-Core]
softdepend: [HolographicDisplays]
description: Contains a large variety of features and functionality to be used specifically for the Aranarth Minecraft server.
loadbefore: [mcMMO, Essentials, VotingPlugin]
commands:
   ac:
      description: All underlying commands regarding the plugin
   aldara:
      description: Provides a link to the map's PlanetMinecraft page
   balance:
      description: Displays the user's balance
      usage: /balance
      aliases: [bal, money]
   balancetop:
      description: Displays a list of users and their balances, showing the highest balance first
      usage: /balancetop
      aliases: [baltop]
   broadcast:
      description: Broadcasts a message to the server
   buy:
      description: Provides the user with the link to the server shop
      usage: /buy
      aliases: [donate]
   eco:
      description: Allows the user to directly modify a player's balance
   map:
      description: Provides the user with a link to view the interactive map
   pay:
      description: Allows the user to pay another player some of their money
   ranks:
      description: Displays the ranks available in the server
   rules:
      description: Provides the user with the server rules
   trails:
      description: Displays all arrow trail effects available to the player's Saint rank
      aliases: [arrows]